version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-710x}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-710x}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    networks:
      - databases
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  databases:
    name: databases
