version: '3.7'

services:
  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "RsCS5RhcxG" ]
    volumes:
      - redis:/data
    networks:
      - databases
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-710x}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-710x}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - databases
    restart: unless-stopped
  
networks:
  databases:
    name: databases

volumes:
  redis:
  postgres:

