version: '3.7'

services:
  express-app:
    image: express
    build: .
    restart: always
    networks:
      - express
      - databases
    logging:
      options:
        max-size: 5m
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

networks:
  express:
    name: express
  databases:
    name: databases
