services:
  dke:
    image: dke
    build: .
    restart: always
    networks:
      - databases
    logging:
      options:
        max-size: 5m
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=production

networks:
  databases:
    name: databases
