services:
  dke:
    image: dke
    build: .
    restart: always
    networks:
      - databases
    logging:
      options:
        max-size: 5m
    ports:
      - 3008:3008
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads

networks:
  databases:
    name: databases
